// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7573b867-b9d1-42fb-b452-0c9e2453eaec"),
                            Author = "Jeyhun",
                            Price = 12m,
                            Title = "1"
                        },
                        new
                        {
                            Id = new Guid("dd930f07-a0b2-482c-8714-5dd8e1d047a1"),
                            Author = "Jeyhun",
                            Price = 12m,
                            Title = "2"
                        },
                        new
                        {
                            Id = new Guid("a18454d5-0bcf-4760-be85-701510455f78"),
                            Author = "Jeyhun",
                            Price = 12m,
                            Title = "3"
                        },
                        new
                        {
                            Id = new Guid("0bec447f-225d-4cde-9cf1-82d55355dde7"),
                            Author = "Jeyhun",
                            Price = 12m,
                            Title = "4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
